feat: Add generic support for testing http/https endpoints.

diff --git a/dockerfile/scripts/common b/dockerfile/scripts/common
--- a/dockerfile/scripts/common
+++ b/dockerfile/scripts/common
@@ -152,6 +152,34 @@ test_cleanup_container() {
     docker kill ${container_name:?} 2>/dev/null 1>&2 || /bin/true
 }
 
+test_http_endpoint() {
+    local container_name="${1:?}"
+    local protocol="${2:?}"
+    local host="${3:?}"
+    local port="${4:?}"
+
+    set +e
+    local http_status_code=$(\
+        curl -w "%{http_code}" --silent --output /dev/null --location "${protocol:?}://${host:?}:${port:?}/")
+    local return_code=$?
+    set -e
+
+    if [[ $return_code != "0" ]]; then
+        echo "Test failed: Obtained non-zero return code"
+        echo "Output: ${http_status_code}"
+        echo "Return Code: ${return_code}"
+        test_cleanup_container ${container_name:?}
+        exit 1
+    fi
+    if [[ ${http_status_code:?} != "200" ]]; then
+        echo "Test failed: Status code is not 200"
+        echo "Output: ${http_status_code}"
+        echo "Return Code: ${return_code}"
+        test_cleanup_container ${container_name:?}
+        exit 1
+    fi
+}
+
 run_test() {
     local container_name=$(test_random_container_name)
 
