feat: Add generic support for testing tcp endpoints.

diff --git a/dockerfile/scripts/common b/dockerfile/scripts/common
--- a/dockerfile/scripts/common
+++ b/dockerfile/scripts/common
@@ -140,6 +140,11 @@ update_packages_install() {
     fi
 }
 
+container_ip() {
+    local container_name="${1:?}"
+    docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${container_name:?}
+}
+
 test_random_container_name() {
     shuf -zer -n16  _ {A..Z} {a..z} {0..9} | tr -d '\0'
 }
@@ -164,17 +169,50 @@ test_http_endpoint() {
     local return_code=$?
     set -e
 
-    if [[ $return_code != "0" ]]; then
+    if [[ ${return_code:?} != "0" ]]; then
         echo "Test failed: Obtained non-zero return code"
-        echo "Output: ${http_status_code}"
-        echo "Return Code: ${return_code}"
+        echo "Output: ${http_status_code:?}"
+        echo "Return Code: ${return_code:?}"
         test_cleanup_container ${container_name:?}
         exit 1
     fi
     if [[ ${http_status_code:?} != "200" ]]; then
         echo "Test failed: Status code is not 200"
-        echo "Output: ${http_status_code}"
-        echo "Return Code: ${return_code}"
+        echo "Output: ${http_status_code:?}"
+        echo "Return Code: ${return_code:?}"
+        test_cleanup_container ${container_name:?}
+        exit 1
+    fi
+}
+
+test_tcp_endpoint() {
+    local container_name="${1:?}"
+    local host="${2:?}"
+    local port="${3:?}"
+    local timeout="${4:?}"
+    local expected_output_regex="${5:?}"
+
+    echo "Testing connectivity with ${container_name:?} through ${host:?}:${port}"
+    set +e
+    local nc_output=$(nc -v -w ${timeout:?} ${host:?} ${port:?})
+    local return_code=$?
+    set -e
+
+    if [[ ${return_code:?} != "0" ]]; then
+        echo "Test failed: Obtained non-zero return code"
+        echo "Output: ${nc_output:?}"
+        echo "Return Code: ${return_code:?}"
+        test_cleanup_container ${container_name:?}
+        exit 1
+    fi
+    if ! [[ "${nc_output:?}" =~ ${expected_output_regex:?} ]]; then
+        local act_hex="$(echo -e "${nc_output:?}" | xxd -p -u)"
+
+        echo "Test failed: Expected and actual outputs do not match"
+        echo "Expected Output Regex: '${expected_output_regex:?}'"
+        echo "Actual Output        : '${nc_output:?}'"
+        echo "Actual Output Hex    : '${act_hex:?}'"
+        echo "Return Code: ${return_code:?}"
         test_cleanup_container ${container_name:?}
         exit 1
     fi
